version: '3.8'

networks:
  default:
    name: working-time

services:
  php-fpm:
    build:
      context: ./dev/docker
      target: development
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      PHP_IDE_CONFIG: "serverName=working-time"

  nginx:
    image: nginx:1.25
    ports:
      - '80'
    networks:
      default:
        aliases:
          - test
    volumes:
      - ./dev/docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    depends_on:
      - php-fpm

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - '3306'
    volumes:
      - ./:/app
    healthcheck:
      test: "/usr/bin/mysql --user=root --host=127.0.0.1 --execute \"SHOW DATABASES;\""
      timeout: 3s
      interval: 1s
      retries: 20
